FROM node:20-alpine

WORKDIR /app

# Install dependencies needed for music-metadata and other native modules
RUN apk add --no-cache git python3 make g++ libc-dev

COPY client/package*.json /app/client/
WORKDIR /app/client
RUN npm install

ENV NODE_ENV=development

CMD ["npm", "run", "dev"]
