FROM node:20-alpine

WORKDIR /app

# Install system dependencies including FFmpeg for audio processing
RUN apk add --no-cache git python3 make g++ libc-dev ffmpeg curl wget openssl

COPY server/package*.json /app/server/
COPY server/prisma /app/server/prisma
WORKDIR /app/server
RUN npm install
RUN npx prisma generate

ENV NODE_ENV=development

CMD ["npm", "run", "dev"]
